system:
  port: ${PORT} # (integer) What port to run the server on
riot-api:
  key: ${RIOT_KEY} # (string) Your Riot API key from https://developer.riotgames.com
  ddversion: '9.24.2' # (string) The Data Dragon version used by Sightstone
  query: null # (integer) Number of games to return from the Riot API
  servers: ["br1", "eun1", "euw1", "jp1", "kr1", "la1", "la2", "na1", "oc1", "tr1", "ru1"] # ([...string]) A list of valid Riot servers
database:
  type: ${DATABASE_TYPE} # What kind of database to use
  uri: ${DATABASE_URI} # (string) Database URI connection string
